vich_uploader:
    db_driver: orm

    mappings:
        picture_user:
            uri_prefix: '%picture_user%'
            upload_destination: '%kernel.project_dir%/public%picture_user%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
